title: 'Encryption '
description: To keep you’re into you’res.
template:
  repo: encryption-template
  name: encryption
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
